packages:
    - ./packages/*
    - ./tests/*
    - ./examples/*

catalogs:
    dep:
        "@standard-schema/spec": ^1.0.0
    dev:
        hono: 4.5.0
        valibot: 1.1.0
        zod: 3.25.6
    peer:
        hono: ^4.5.0
        zod: ^3.25.6 || ^4.0.0
    test:
        vitest: ^4
    example:
        "@types/node": ^25
        "@hono/node-server": ^1
        "@hono/vite-dev-server": ~0.23.0
        "@hono/vite-build": ^1
        "vite": ^7
        "vite-tsconfig-paths": ^6

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "@jderstd/core"
    - "ts-vista"
