packages:
    - ./packages/*
    - ./tests/*
    - ./examples/*

catalogs:
    dep:
        "@standard-schema/spec": ^1.0.0
    dev:
        hono: 4.5.0
        valibot: 1.1.0
        zod: 3.25.6
    peer:
        hono: ^4.5.0
        zod: ^3.25.6 || ^4.0.0
    test:
        vitest: ^4.0.8
    example:
        "@types/node": ^24.10.1
        "@hono/node-server": ^1.19.6
        "@hono/vite-dev-server": ~0.23.0
        "@hono/vite-build": ^1.7.0
        "vite": ^7.2.2
        "vite-tsconfig-paths": ^5.1.4

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@jderstd/core"
    - "ts-vista"
