packages:
    - ./packages/*
    - ./tests/*
    - ./examples/*

catalogs:
    dep:
        "@standard-schema/spec": ^1.0.0
    dev:
        hono: 4.5.0
        valibot: 1.1.0
        zod: 3.25.6
    peer:
        hono: ^4.5.0
        zod: ^3.25.6 || ^4.0.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@jderstd/core"
    - "ts-vista"
